POLICY = {
    "MAX_DELAY_DAYS_AUTO_RESOLVE": 2,
    "MIN_INVENTORY_DAYS_FOR_AUTO_RESOLVE": 7,
    "MIN_SUPPLIER_RELIABILITY_FOR_AUTO_RESOLVE": 0.80,  # placeholder until supplier context is added
    "ESCALATE_IF_PRIORITY": True,
    "ESCALATE_IF_ORDER_VALUE_GTE": 100000,
}